### ISSUE TITLE
Undersøg automatisering af bestilling via lokal IdP

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/bestil-journaliser-attester#10]
Lokal IdP: https://digst.dk/it-loesninger/nemlog-in/om-loesningen/aendring-i-funktionaliteter/lokal-idp/

```[tasklist]
### Tasks
- [x] Undersøg mulighed for at automatisere bestilling af straffeattester ved Politiet vha. lokal IdP-login
- [x] Undersøg mulighed for at implementere og bruge npm-modul til authentication key-generation
- [ ] Undersøg mulighed for delvis automatiseret bestilling af attester
```
