### ISSUE TITLE
Klargør til deployment

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/bestil-journaliser-attester#27]
```[tasklist]
### Tasks
- [ ] https://github.com/Randers-Kommune-Digitalisering/bestil-journaliser-attester/issues/44
- [ ] https://github.com/Randers-Kommune-Digitalisering/bestil-journaliser-attester/issues/51
- [ ] https://github.com/Randers-Kommune-Digitalisering/bestil-journaliser-attester/issues/14
- [ ] https://github.com/Randers-Kommune-Digitalisering/bestil-journaliser-attester/issues/69
- [x] Ryd test data (test rekvirent + udvikler mail-adresser i konfiguration)
- [ ] https://github.com/Randers-Kommune-Digitalisering/bestil-journaliser-attester/issues/63
- [ ] https://github.com/Randers-Kommune-Digitalisering/bestil-journaliser-attester/issues/72
```
