### ISSUE TITLE
Opsæt rolle i KeyCloak

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/bestil-journaliser-attester#51]
```[tasklist]
### Tasks
- [x] Opsæt applikation i KeyCloak
- [x] Opsæt rolle til adgang i KeyCloak
- [x] Fix problem med rolleadgang
```
