### ISSUE TITLE
Fix mail HTML struktur

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/bestil-journaliser-attester#55]
Mails-kroppe som videresendes med HTML indhold parses skal virke efter hensigten.

Test følgende:

```[tasklist]
### Tasks
- [x] Videresendelse af mail med HTML-elementer
- [x] Videresendelse af mail med klartekst
- [x] Videresendelse af mail med vedhæftning
- [x] Videresendelse af mail med med både HTML-elementer og vedhæftning
```
