### ISSUE TITLE
Find korrekt personalesag før journalisering

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/bestil-journaliser-attester#6]
Pt. fremsøges en manuelt oprettet test-sag fra SBSYS test med test-CPR.

```[tasklist]
### Tasks
- [x] Find relevante personalesager for aktuelt CPR
- [x] Send til manuel behandling hvis flere personalesager findes på samme person
- [x] Send mail ved manuel behandling
```

Såfremt flere (aktive?) personalesager findes på samme CPR, skal attesten sendes til manuel behandling med email.
Såfremt ingen personalesager findes, skal attesten ligeledes sendes til manuel behandling.
