### ISSUE TITLE
Udvidet bestillingshistorik 

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/bestil-journaliser-attester#64]
```[tasklist]
### Tasks
- [x] Mulighed for manuel sortering
- [x] Forbedring af standard-sortering (dato > attest-type > rekvirent)
- [x] Mulighed for at se længere historik (100 elementer)
- [x] Søgefunktionalitet i historik
- [ ] Bestillingshistorik med noteret bestillingsansvarlig
- [ ] Farvekoder på datoer ift. hvor længe siden attester er blevet bestilt (afventer modtagelse)
```
